# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE (2nd generation)"
])

languages([
  "en-US"
  # "ru-RU",
  # "de-DE",
  # "ar",
  # "zh-Hans",
  # "zh-Hant",
  # "cs",
  # "da",
  # "nl",
  # "fr",
  # "es",
  # "ja",
  # "ko",
  # "vi",
  # "th",
  # "nb",
  # "tr",
  # "he",
  # "ro",
  # "ms",
  # "pt-BR",
  # "sv",
  # "hu",
  # "id",
  # "pl",
  # "fi",
  # "it-IT"
])

# The name of the scheme which contains the UI Tests
scheme("ScreenshotsTests")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)
skip_open_summary(true)
concurrent_simulators(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
